name: sign_learn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/bye.png
  - assets/chocolate.png
  - assets/excuse_me.png
  - assets/good_morning.png
  - assets/good.png
  - assets/happy.png
  - assets/hello.png
  - assets/i_love_you.png
  - assets/please.png
  - assets/sad.png
  - assets/thank_you.png
  - assets/when.png
